
rapid_build:
	clear
	g++ -g -Wall ./src/main.cpp -o metmice --std=c++17

build:
	g++ -g -Wall -O3 ./src/main.cpp -o metmice --std=c++17

debug:
	g++ -g --std=c++17 ./src/main.cpp -o metmice -pedantic -Wall -Wextra -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wdisabled-optimization -Wformat=2 -Winit-self -Wmissing-declarations -Wmissing-include-dirs -Wold-style-cast -Woverloaded-virtual -Wredundant-decls -Wshadow -Wsign-conversion -Wsign-promo -Wstrict-overflow=5 -Wswitch-default -Wundef -Werror -Wno-unused
